### ISSUE TITLE
How do I get the size of size_t?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/sbnw#36]
Some routines eg getNumOfComps returns size_t. For an external application that calls this function, how can they find out the size of size_t? Currently I am assuming unsigned 64 bit integer.

**Comment by luciansmith** [comment]
External applications can (and should) also use 'size_t'.  Unless I'm misunderstanding the question?

At the moment, 'size_t' is equivalent to 'unsigned int' on most platforms.  But I've seen cases where this was not true--when I was working on lamarc when linux was switching to 64-bit from 32-bit, we had a case on at least one platform where ints were still 32-bit, but size_t was 64.  They aren't required to be exactly the same.

**Comment by 0u812** [comment]
It's platform-specific (ref: http://stackoverflow.com/questions/2550774/what-is-size-t-in-c). On win32 it will be 32-bit, but on win64 it will be 64-bit.

I can implement a function to return the size of size_t so you can do a runtime check on your end for `sizeof(my_size_t_type) = gf_get_size_of_size_t()`.

**Comment by 0u812** [comment]
Actually apparently you can't even count on it being 32-bit (https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751%28v=vs.85%29.aspx).

Which functions are you using that return/require `size_t`? I can just make them use 64-bit unsigned ints instead.

**Comment by hsauro** [comment]
Note I'm calling it from Delphi so I've no idea what the size it is coming from the library.

**Comment by hsauro** [comment]
For applications that call the library the size of the size_t type should be documented so that they know how to deal with the function. 64-bit unsigned int will work.

**Comment by 0u812** [comment]
What functions are you using?

**Comment by hsauro** [comment]
Things like get number of reactions, species and compartments

**Comment by luciansmith** [comment]
If you need the size of size_t, you should be able to get that exactly the same way you get the size of int, char, double, etc.

For language bindings, that decision is made when you create the binding, and the documentation should reflect that.

It's important to use size_t and not unsigned int, because size_t is actually the size of the arrays in question, and the size of the arrays in question varies per platform.  If the arrays are 32-bit, they can be indexed up to exactly that size and no more--you'll get errors if you try to go further.  If the arrays are 64-bit, they can be indexed up to that size, and you'll potentially lose data if you restrict it.

(Of course, having billions of compartments is somewhat unlikely--you could sweep everything under the rug by using the smaller size, and make everyone limit themselves to a few billion compartments instead of several billion compartments.)

**Comment by 0u812** [comment]
Binaries with fix:
https://sourceforge.net/projects/sbnw/files/1.3.11

**Comment by 0u812** [comment]
In the above fix I'm using unsigned 64 bit integers for all functions which used to use size_t.

**Comment by 0u812** [comment]
Docs are also updated btw
